steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - cloud-and-proud
  - --source=.
  - --runtime=python37
  - --trigger-http
  - --memory=256MB
  - --timeout=42
  - --set-env-vars=name=$(gcloud beta secrets versions access --secret=andrew-demo latest)
  - --allow-unauthenticated
  - --entry-point=hello